server:
  port: 8001

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://admin:Haier2020@localhost:8000/eureka

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        # 设置为false，以便在未找到应用程序的情况下Server返回HTTP 404状态。默认情况下，此标志设置为true
        accept-empty: false
        git:
          #uri: https://github.com/wangchaodz/mos-config-server
          uri: file:///E:\git\mos-config-server
          # 设置为true（默认值为false）来禁用配置服务器对Git服务器的SSL证书的验证
          skipSslValidation: true
          username:
          password:
          # 配置服务器将等待获取HTTP连接的时间（以秒为单位）
          timeout: 4
          search-paths: config
          # 可以使用这个配置项来指定本地git仓库的路径
          #basedir: E:\git\mos-config-server
          # github的分支，默认是master
          default-label: master
  profiles:
    active: dev
