server:
  port: 8004
spring:
  application:
    name: server-api-user
  cloud:
    # Bus 相关配置项，对应 BusProperties
    bus:
      # 是否开启，默认为 true
      enabled: true
      # 目标消息队列，默认为 springCloudBus
      destination: springCloudBus
    
    # rocketmq 配置项，对应 RocketMQProperties 配置类
    stream:
      rocketmq:
        binder:
          # RocketMQ Namesrv
          name-server: 127.0.0.1:9876

  #zipkin-server地址
  zipkin:
    base-url: http://localhost:9411/
  #接口默认全部采样
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://admin:Haier2020@localhost:8000/eureka
